### ISSUE TITLE
Add "Donate" button

### ISSUE THREAD

**Issue by philhawksworth** [philhawksworth/the-united-effort-orginization#5] opened 2022-04-22 13:58 UTC
Add a "Donate" button into the donation component on each page which sends the user into a PayPal donation flow.

Prerequisite for this is having details of a suitable PayPal account,

**Comment by trevorshannon** [comment] 2022-06-02 20:11
closing as duplicate of #129

**Closed** 2022-06-23 04:42 UTC
Labels: enhancement
